
[workspace]

members = [
    "sim",
    "gui",
    "enum_macros",
    "eco_sim_py/ffi",
    "eval",
]

default-members = [
    "sim",
    "gui",
    "enum_macros",
    "eco_sim_py/ffi",
]

[profile.dev]
opt-level = 3

[profile.test]

[profile.release]
