[package]
name = "eco_sim"
version = "0.1.0"
authors = ["Feisal Schlee <fschlee@techfak.uni-bielefeld.de>"]
edition = "2018"

[dependencies]
"log" = "^0.4"

"rand" = "^0.7"
"rand_xorshift" = "^0.2"
"rand_distr" = "^0.2.2"

"strum" = "^0.16"
"strum_macros" = "^0.16"
