[package]
name = "enum_macros"
version = "0.1.0"
authors = ["Feisal Schlee <fschlee@techfak.uni-bielefeld.de>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "^1.0.8"
quote = "^1.0.2"